name: RPA

on:
  schedule:
    # Rougly 10PM UTC, or 6AM to 10AM GMT8 factoring in delays and DST
    - cron: "0 22 * * *"

  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Start RPA
        env:
          SFOS_URL: "${{ secrets.SFOS_URL }}"
          SFOS_USER: "${{ secrets.SFOS_USER }}"
          SFOS_PKEY: "${{ secrets.SFOS_PKEY }}"
          GSUITE_USER: "${{ secrets.GSUITE_USER }}"
          GSUITE_PKEY: "${{ secrets.GSUITE_PKEY }}"
          GDRIVE_FI_RECEIPTS_ID: "${{ secrets.GDRIVE_FI_RECEIPTS_ID }}"
          GSHEETS_FI_REV_X_EXP_TRACKER_ID: "${{ secrets.GSHEETS_FI_REV_X_EXP_TRACKER_ID }}"
          GSHEETS_SI_SALES_TRACKER_ID: "${{ secrets.GSHEETS_SI_SALES_TRACKER_ID }}"
          GSHEETS_HR_PAYOUT_TRACKER_ID: "${{ secrets.GSHEETS_HR_PAYOUT_TRACKER_ID }}"
          GMAIL_USER: "${{ secrets.GMAIL_USER }}"
          GMAIL_PKEY: "${{ secrets.GMAIL_PKEY }}"
          SENDER_EMAIL_CONTACT_NO: "${{ secrets.SENDER_EMAIL_CONTACT_NO }}"
          ACCTG_EMAIL_ADDRESSEE: "${{ secrets.ACCTG_EMAIL_ADDRESSEE }}"
          ACCTG_EMAIL_RECIPIENTS: "${{ secrets.ACCTG_EMAIL_RECIPIENTS }}"
          ACCTG_EMAIL_RECIPIENTS_CC: "${{ secrets.ACCTG_EMAIL_RECIPIENTS_CC }}"
          STAFF_EMAIL_RECIPIENTS: "${{ secrets.STAFF_EMAIL_RECIPIENTS }}"
          STAFF_EMAIL_RECIPIENTS_CC: "${{ secrets.STAFF_EMAIL_RECIPIENTS_CC }}"
          TELEGRAM_BOT_KEY: "${{ secrets.TELEGRAM_BOT_KEY }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"
          PARALLEL: "0"
          HEADLESS: true
        run: npm start
      - name: Post RPA cleanup
        run: |
          echo Removing downlaods
          rm -rf downloads/
      - name: Upload Artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/report.html
          retention-days: 3
